{"summary":"用于在DataWorks平台使用过程中触发扩展点时，通过调用CallbackExtension接口，将扩展程序对扩展点事件的检查结果返回给DataWorks平台。","methods":["post"],"schemes":["https"],"security":[{"AK":[]}],"operationType":"readAndWrite","deprecated":false,"systemTags":{"operationType":"none","riskType":"none","chargeType":"free","abilityTreeCode":"191317","abilityTreeNodes":["FEATUREdideRWC5F7"]},"parameters":[{"name":"ExtensionCode","in":"formData","schema":{"description":"扩展程序唯一编码。","type":"string","required":true,"example":"8abcb91f-d266-4073-b907-2ed670378ed1"}},{"name":"MessageId","in":"formData","schema":{"description":"DataWorks开放消息的消息ID。当触发扩展点事件后，您可以从接收到的事件消息中获取消息ID。\n\n<props=\"china\">消息格式，可参考[消息格式](~~215367~~)。</props>\n\n","type":"string","required":true,"example":"03400b03-b721-4c34-8727-2d6884077091"}},{"name":"CheckResult","in":"formData","schema":{"description":"扩展程序对本次扩展点事件的检查状态。取值如下：\n- OK：扩展程序对本次扩展点事件检查通过。\n- FAIL：扩展程序对本次扩展点事件检查不通过。您需要查看并及时处理报错，以免影响后续程序的正常执行。\n- WARN：扩展程序对本次扩展点事件检查通过，但存在警告。","type":"string","required":true,"example":"FAIL","enum":["OK","FAIL","WARN"]}},{"name":"CheckMessage","in":"formData","schema":{"description":"当CheckResult设置为FAIL，提供FAIL原因","type":"string","required":false,"example":"命中xxx规则，请修改后重试"}}],"responses":{"200":{"schema":{"title":"Schema of Response","description":"返回结果","type":"object","properties":{"RequestId":{"title":"Id of the request","description":"唯一的请求ID","type":"string","example":"7C352CB7-CD88-50CF-9D0D-E81BDF020E7F"},"Success":{"description":"调用是否成功。取值如下：\n\ntrue：调用成功。\n\nfalse：调用失败。","type":"string","example":"true"}}}}},"staticInfo":{"returnType":"synchronous"},"responseDemo":"[{\"errorExample\":\"\",\"example\":\"{\\n  \\\"RequestId\\\": \\\"7C352CB7-CD88-50CF-9D0D-E81BDF020E7F\\\",\\n  \\\"Success\\\": \\\"true\\\"\\n}\",\"type\":\"json\"}]","title":"返回扩展程序对扩展点事件的检查结果"}